### ISSUE TITLE
Improve tokenization

### ISSUE THREAD

**Issue by shiffman** [ml5js/training-word2vec#1]
The `train.py` script splits the input text into sentences and words. This could be vastly improved with better regex or a package like [nltk](https://www.nltk.org/).

```python
# Split into sentences (this could be improved! Using nltk?)
sentences = re.split("[.?!]", text)

# Split each sentence into words! (this could also be improved!)
final_sentences = []
for sentence in sentences:
    words = re.split("\W+", sentence)
    final_sentences.append(words)
```

**Comment by patricoferris** [comment]
Happy to start looking into this when I have some time - do you think this should be part of the optional arguments that you can add mentioned in #2? For example it could be nice to have the [Tweet Tokenizer](http://www.nltk.org/api/nltk.tokenize.html) option.

**Comment by shiffman** [comment]
@patricoferris yes, it definitely would be! But I think even just a more robust default way of extracting sentences and words would be a good place to start.

**Comment by patricoferris** [comment]
Okay great @shiffman, I will probably get some time over the weekend to have a look into this. Do you think using something like [NLTK-Punkt](https://www.nltk.org/_modules/nltk/tokenize/punkt.html) would be good for sentence tokenization, and then a standard NLTK class for the words? 

This [site](https://text-processing.com/demo/tokenize/) is a cool way to see how the different classes treat different words, particularly things like "*can't*" or "*don't*". Is there are any preference in the way you want these to be handled? What's also great is that there is some support for multiple languages too!

**Comment by headwinds** [comment]
@patricoferris @shiffman this really is a cool project - any updates? Along with NLTK, we could also include a [spaCy version](https://medium.com/@makcedward/nlp-pipeline-sentence-tokenization-part-6-86ed55b185e6) and possibly standford NLP too. I would be happy to help test and fan the flame.

**Comment by ippo615** [comment]
I've added nltk tokenization in pull request #8

**Comment by shiffman** [comment]
Thank you @ippo615! If we want to improve the tokenization or add other options as suggested (a year ago!) by @headwinds we can create new issues.
