### ISSUE TITLE
how can i use this code in php? 

### ISSUE THREAD

**Issue by Nasidiqi** [ml5js/training-word2vec#7]
I want to use word2vec in php. can u help how ?

**Comment by ippo615** [comment]
You can use php's `exec` function to call external python scripts. The php documentation has more info: https://www.php.net/manual/en/function.exec.php

Here is sample of what you may want to do:

```php
$output = exec('python /path/to/train.py /path/to/files/ -o /path/to/output.json', $retval);
```

Your json file will be saved in `/path/to/output.json`. Of course, you'll need to specify the appropriate paths to the script and your files and add any additional arguments.

There may be an implementation of word2vec training for php which you may prefer to use -- but I didn't find one (I also didn't spend a lot of time looking).

**Comment by shiffman** [comment]
Thanks for responding @ippo615!
